version: '3.7'

services:
  api:
    image: reviewdb-api
    container_name: reviewdb-api
    build: ./server
    command: sh -c "yarn start"
    volumes:
      - ./server/:/usr/src/app
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  frontend:
    image: reviewdb-frontend
    container_name: reviewdb-frontend
    build: ./frontend
    command: sh -c "npm run dev"
    volumes:
      - ./frontend/:/usr/src/app/
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev.client
    depends_on:
      - api

  postgres:
    image: postgres
    container_name: reviewdb-postgres
    volumes:
     - reviewdb-postgres:/var/lib/postgresql/data/
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev.db

  pgadmin:
    container_name: reviewdb-pgadmin
    image: dpage/pgadmin4
    env_file: 
      - ./.env.dev.pgadmin
    ports:
      - 5050:80

volumes:
 reviewdb-postgres:
