version: '3.7'

services:
  api:
    image: reviewdb-backend
    container_name: reviewdb-backend
    build: ./backend
    command: sh -c "npm run dev"
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: reviewdb_db
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./.env.dev.db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./.env.dev.db
    depends_on:
      - mongo
    

